#!/bin/bash -efu

case "$method" in
ftp|http|url)
	ALTBOOT="waitnet,download"
	if grep -qws ramdisk_size /proc/cmdline; then
		VALUE="method=$method;to=RD;fuid=$STAGENAME"
	elif [ "$type" != iso ]; then
		VALUE="method=$method;to=TMPFS;fuid=$STAGENAME"
	else
		if [ -n "${HASH-}" ]; then
			ALTBOOT="$ALTBOOT,checksum"
			ALTBOOT_CHECKSUM0="$HASH"
			HASH=
		fi
		VALUE="method=$method;to=TMPFS"
		ALTBOOT="$ALTBOOT,iso9660"
	fi
	if [ "$method" = url ]; then
		VALUE="$VALUE;url=$url"
	elif [ -n "$server" ] || [ -n "$directory" ]; then
		VALUE="$VALUE;server=$server;directory=$directory"
		[ -z "$user" ] || [ "$method" = http ] ||
			VALUE="$VALUE;user=$user;pass=$pass"
	fi
	[ -z "$imgsize" ] ||
		VALUE="$VALUE;imgsize=$imgsize"
	[ -z "$timeout" ] ||
		VALUE="$VALUE;timeout=$timeout"
	ALTBOOT_DOWNLOAD0="$VALUE"
	overlays=
	LOWMEM=1
	VALUE=
	;;
esac
