#!/bin/bash -efu

case "$method" in
ftp|http|url)
	VALUE="method=$method"
	if [ "$method" = "url" ]; then
		VALUE="$VALUE;to=RD;url=$url"
	else
		grep -qws ramdisk_size /proc/cmdline &&
			VALUE="$VALUE;to=RD" || VALUE="$VALUE;to=TMPFS"
		if [ -n "$server" ] || [ -n "$directory" ]; then
			VALUE="$VALUE;server=$server;directory=$directory"
			[ -z "$user" ] || [ "$method" != "ftp" ] ||
				VALUE="$VALUE;user=$user;pass=$pass"
		fi
	fi
	[ -z "$imgsize" ] ||
		VALUE="$VALUE;imgsize=$imgsize"
	[ -z "$timeout" ] ||
		VALUE="$VALUE;timeout=$timeout"
	ALTBOOT="download,iso9660"
	ALTBOOT_DOWNLOAD0="$VALUE"
	overlays=
	LOWMEM=1
	VALUE=
	;;
esac
