#!/bin/bash -efu

if [ -n "${LOWMEM-}" ]; then
	if [ -n "${HASH-}" ]; then
		ALTBOOT="$ALTBOOT,checksum"
		ALTBOOT_CHECKSUM0=":$HASH:/$STAGENAME"
	fi

	ALTBOOT="$ALTBOOT,squashfs"
	ALTBOOT_SQUASHFS0="/$STAGENAME"
else
	ALTBOOT="$ALTBOOT,download"
	ALTBOOT_DOWNLOAD0="method=url;to=RD;url=file:///$STAGENAME"

	if [ -n "${HASH-}" ]; then
		ALTBOOT="$ALTBOOT,checksum"
		ALTBOOT_CHECKSUM0="$HASH"
	fi

	ALTBOOT="$ALTBOOT,squashfs"
	ALTBOOT_SQUASHFS0="-"
fi
