#!/bin/bash -efu

if [ -n "${LOWMEM-}" ]; then
	if [ -n "${HASH-}" ]; then
		ALTBOOT="$ALTBOOT,checksum"
		ALTBOOT_CHECKSUM0=":$HASH:/$STAGENAME"
	fi

	ALTBOOT="$ALTBOOT,squashfs"
	ALTBOOT_SQUASHFS0="/$STAGENAME"
else
	ALTBOOT="$ALTBOOT,copyfile"
	ALTBOOT_COPYFILE0="src=/$STAGENAME"
	grep -qws ramdisk_size /proc/cmdline ||
		ALTBOOT_COPYFILE0="dst=TMPFS;$ALTBOOT_COPYFILE0"

	if [ -n "${HASH-}" ]; then
		ALTBOOT="$ALTBOOT,checksum"
		ALTBOOT_CHECKSUM0="$HASH"
	fi

	ALTBOOT="$ALTBOOT,squashfs"
	ALTBOOT_SQUASHFS0="-"
fi
