#!/bin/bash -efu

. altboot-sh-functions

check_parameter ALTBOOT_CHECKSUM

check=
hashprog=
filename=
fullpath=
datasize=0


check_prevstep_results()
{
	[ -n "$prevdir" ] ||
		return 1
	enter "check_prevstep_results"

	if [ "${filename:0:1}" = "/" ]; then
		fullpath="${prevdir}${filename}"
		mountpoint -q -- "$prevdir" && [ -r "$fullpath" ] ||
			return 1
		datasize="$(run stat -L -c%s -- "$fullpath" ||:)"
		[ -n "$datasize" ] ||
			return 1
	elif [ -r "$prevdir/DEVNAME" ]; then
		[ -r "$prevdir/FILESIZE" ] &&
		read -r filename <"$prevdir/DEVNAME" &&
		read -r datasize <"$prevdir/FILESIZE" &&
		[ -b "$filename" ] && [ -n "$datasize" ] ||
			return 1
		fullpath="$filename"
	else
		[ -b "$prevdir/dev" ] &&
		[ -r "$prevdir/FILESIZE" ] &&
		read -r datasize <"$prevdir/FILESIZE" &&
		[ -n "$datasize" ] ||
			return 1
		filename="$prevdir/dev"
		fullpath="$filename"
	fi

	leave "check_prevstep_results"
}


# CHECKSUM=<HASH> -or-
# CHECKSUM=[<hashprog>]:<HASH> -or-
# CHECKSUM=[<hashprog>]:<HASH>:<filename>
# Example: md5sum:01234567890123456789:/live

get_bootarg CHECKSUM

# Entry point
debug "$PROG started ($CHECKSUM)"

if [ "$CHECKSUM" != "${CHECKSUM#*:}" ]; then
	hashprog="${CHECKSUM%%:*}"
	CHECKSUM="${CHECKSUM#*:}"
	if [ "$CHECKSUM" != "${CHECKSUM#*:}" ]; then
		filename="${CHECKSUM#*:}"
		CHECKSUM="${CHECKSUM%%:*}"
	fi
fi
hashprog="${hashprog:-sha256sum}"
command -v "$hashprog" >/dev/null ||
	fatal "hash program not found: $hashprog"
[ -n "$CHECKSUM" ] ||
	fatal "hash summa not specified"
[ -z "$prevdir" ] ||
	prevdir="$(readlink-e "$prevdir")"
check_prevstep_results ||
	fatal "no previous step results to use with $PROG"
[ "$datasize" -gt 0 ] 2>/dev/null ||
	fatal "invalid data size: $datasize"

message "hash summa: $CHECKSUM"
message "hash data size: $datasize"
message "hash check program: $hashprog"
message "calculating image checksum on the '$filename'..."

IM_on

(pv -n -i 0.25 -s $datasize -- "$fullpath" |"$hashprog" |
	cut -f1 -d' ' >"$datadir/CHECKSUM") 2>&1 |
	IM_gauge "[ Validating image... ]"
[ -r "$datadir/CHECKSUM" ] &&
	read -r check <"$datadir/CHECKSUM" ||
	check="not checked"
rm -f -- "$datadir/CHECKSUM"
message "calculated hash: $check"

[ "$CHECKSUM" = "$check" ] || [ -n "$NOASK" ] ||
	IM_errmsg "Image file checksum mismatch!"

IM_off

[ "$CHECKSUM" = "$check" ] ||
	fatal "image file checksum mismatch"
message "checksum verified successfully"

passthru_results
debug "$PROG finished"
