#!/bin/bash -efu

. altboot-sh-functions

pv=

message "$PROG for $name [$callnum] started"

if [ -n "$prevdir" ]; then
	pv="$(readlink-e "$prevdir" ||:)"
	[ -d "$pv" -a "$pv" != "$prevdir" ] || pv=
fi

message "PREV DIR: ${prevdir}${pv:+ ($pv)}"
message "Data DIR: $datadir"
message "DEST DIR: $destdir"

{ printf "##############################"

  if [ -d "$prevdir" ]; then
	printf "\nPrevious step results (%s):\n" "${pv:-$prevdir}"
	ls "$prevdir/"
  fi

  if mount |grep -q "/dev/pipeline/"; then
	printf "\nMount points and devices:\n"
	mount |grep "/dev/pipeline/"
  fi

  printf "##############################\n"
} 1>&2

message "$PROG for $name [$callnum] finished"
