#!/bin/bash -efu

. altboot-sh-functions

devname=
mp="$destdir"

[ -z "$prevdir" ] ||
	prevdir="$(readlink-e "$prevdir")"
[ -n "$prevdir" ] && [ -r "$prevdir/DEVNAME" -o -b "$prevdir/dev" ] ||
	fatal "no previous step results to use with $PROG"
[ -r "$prevdir/DEVNAME" ] && read -r devname <"$prevdir/DEVNAME" ||
	devname="$prevdir/dev"
[ -b "$devname" ] ||
	fatal "block special device not found: $devname"

[ -z "$ALTBOOT_STAGE2COMPAT" ] ||
	mp="${OEM_CDIMAGE_PATH:-/image}"
run mkdir -p -- "$mp"
run mount -t iso9660 -o ro -- "$devname" "$mp" ||
	fatal "can't mount target drive: $devname"
[ -z "$ALTBOOT_STAGE2COMPAT" ] ||
	passthru_results "$mp"
