#!/bin/bash -efu

. pipeline-sh-functions

[ -z "$prevdir" ] ||
	prevdir="$(readlink-e "$prevdir")"
[ -n "$prevdir" ] ||
	fatal "no previous step to use as rootfs"

[ "$prevdir" = "$rootmnt" ] ||
	run mount --move "$prevdir" "$rootmnt"
echo localdev > /etc/initrd/method
exit 2
