#!/bin/bash -efu

case "$method" in
cdrom|disk)
	ALTBOOT=localdev
	VALUE="method=$method"

	if [ "$method" = cdrom ]; then
		directory=
		partition=
	else
		[ -z "$directory" ] ||
			VALUE="$VALUE;directory=$directory"
		[ -z "$partition" ] ||
			VALUE="$VALUE;part=$partition"
	fi

	[ -z "$disk" ] ||
		VALUE="$VALUE;disk=$disk"
	[ -z "$fuid" ] ||
		VALUE="$VALUE;fuid=$fuid"
	[ -z "$uuid" ] ||
		VALUE="$VALUE;uuid=$uuid"
	[ -z "$label" ] ||
		VALUE="$VALUE;label=$label"
	[ -z "$options" ] ||
		VALUE="$VALUE;options=$options"
	[ -z "$timeout" ] ||
		VALUE="$VALUE;timeout=$timeout"
	[ -z "${UPDATEMODULES-}" ] ||
		ALTBOOT="oemsetup,$ALTBOOT"
	ALTBOOT_LOCALDEV0="$VALUE;squash=$STAGENAME"
	VALUE=
	;;
esac
