#!/bin/bash -efu

case "$overlayroot" in
tmpfs)	live_rw=1
	;;
'')	overlayroot=tmpfs
	live_rw=1
	;;
UUID=?*)
	[ ! -L "/dev/disk/by-uuid/${overlayroot#UUID=}" ] ||
		live_rw="/dev/disk/by-uuid/${overlayroot#UUID=}"
	;;
LABEL=?*)
	[ ! -L "/dev/disk/by-label/${overlayroot#LABEL=}" ] ||
		live_rw="/dev/disk/by-label/${overlayroot#LABEL=}"
	;;
/dev/?*)
	[ ! -b "$overlayroot" ] ||
		live_rw="$overlayroot"
	;;
esac

if [ "$overlayroot" = disabled ]; then
	if grep -qs " $prevdir squashfs " /proc/mounts; then
		overlayroot=tmpfs
		live_rw=1
	fi
elif [ -z "$live_rw" ] && [ -n "$overlayroot" ]; then
	message "overlayroot will be ignored: '$overlayroot'"
	overlayroot=
fi
