#!/bin/bash -efu

. bootchain-sh-functions

launch_step_once
[ -n "$prevdir" ] && mountpoint -q -- "$prevdir" ||
	fatal "no previous step to use as rootfs"

while ! resume_checked; do
	sleep 0.5
done

[ "$prevdir" = "$rootmnt" ] ||
	run mount --move -- "$prevdir" "$rootmnt"
break_bc_loop
