#!/bin/bash -efu

. bootchain-sh-functions

launch_step_once
[ -n "$prevdir" ] && mountpoint -q -- "$prevdir" ||
	fatal "no previous step to use as rootfs"

while ! resume_checked; do
	sleep 0.5
done

# shellcheck disable=SC2119
bypass_results

break_bc_loop
