MODULES_TRY_ADD += $(BOOTCHAIN_MODULES)
MODULES_PRELOAD += $(BOOTCHAIN_PRELOAD)

PUT_FEATURE_DIRS += $(BOOTCHAIN_DATADIR)
PUT_FEATURE_FILES += $(BOOTCHAIN_FILES)
PUT_FEATURE_PROGS += $(BOOTCHAIN_PROGS)
