#!/bin/bash
### BEGIN INIT INFO
# Provides:            bootchain
# Required-Start:      uevent udev
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /.initrd/initenv
. /etc/init.d/template

NAME=chaind
PIDFILE="/var/run/$NAME.pid"
ARGS="--lockfile $LOCKFILE --pidfile $PIDFILE --name $NAME --displayname $NAME"

start() {
	RETVAL=0
	if [ "${ROOT-}" = bootchain ] || [ "${ROOT-}" = pipeline ]; then
		start_daemon --background $ARGS "$NAME"
		RETVAL=$?
	fi
	return $RETVAL
}

stop() {
	stop_daemon $ARGS "$NAME"
	RETVAL=$?
	rm -f -- "$PIDFILE"
	return $RETVAL
}

switch "${1-}"
